### ISSUE TITLE
I want to konw where can i get the dataset?

### ISSUE THREAD

**Issue by PeifengRen** [ku-milab/DA-BCI#1]
Is it convenient for you to share your dataset in a special format？Thank you

**Comment by wltjr1007** [comment]
Sorry, we cannot distribute the dataset since we do not own it (and may go against owner's rights). 
Please refer to our [paper](https://doi.org/10.1109/IWW-BCI.2019.8737340) for preparation of the dataset. We will be happy to answer any questions you may have.

cc. @eunjin93

**Comment by PeifengRen** [comment]
OK，Thank you !



发自我的iPhone


------------------ Original ------------------
From: Yoon, Jee Seok ***@***.***&gt;
Date: Wed,Jul 21,2021 4:50 PM
To: ku-milab/DA-BCI ***@***.***&gt;
Cc: peifeng_ren ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ku-milab/DA-BCI] I want to konw where can i get the dataset? (#1)





 
Sorry, we cannot distribute the dataset since we do not own it (and may go against owner's rights).
 Please refer to our paper for preparation of the dataset. We will be happy to answer any questions you may have.
 
@eunjin93
